version: '2'

services:
  web:
    build: 
      context: web/
    volumes:
      - './web:/var/www/html'
    ports:
      - 8081:80

  db:
    ports:
      - 5432:5432

  node:
    image: node:5.8-onbuild
    working_dir: /var/www/html
    ports:
      - 3000:3000
      - 3001:3001
    volumes_from: 
      - web
    networks:
      - front-tier  

